version: "3.8"

services:
  # --------------------------------------------------------------------------------
  ecommerce-app:
    build:
      context: .
      dockerfile: ./dockerfiles/app.dockerfile
    container_name: ecommerce-app
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - ecommerce-net
    depends_on:
      - ecommerce-postgres
      - ecommerce-redis
  # --------------------------------------------------------------------------------
  ecommerce-postgres:
    image: postgres:alpine
    container_name: ecommerce-postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
    volumes:
      - ecommerce-postgres-data:/var/lib/postgresql/data
      - ./migrations:/migrations
    networks:
      - ecommerce-net
  # --------------------------------------------------------------------------------
  ecommerce-redis:
    image: redis:alpine
    container_name: ecommerce-redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - ecommerce-net
  # --------------------------------------------------------------------------------

networks:
  ecommerce-net:
    driver: bridge

volumes:
  ecommerce-postgres-data:
