version: "3.7"

services:
  # # Golang app
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./dockerfiles/app.dockerfile
  #   container_name: app
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - net
  #   depends_on:
  #     - database

  # Database
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
    volumes:
      - /home/docker/volumes/postgres:/var/lib/postgresql/data
      - ./migrations:/migrations
    networks:
      - net

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - net

networks:
  net:
    driver: bridge
